on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: "build.yaml"

---
include:
  - board: seeed_xiao_ble_nrf52840
    shield: KeyballBLE_R
  - board: seeed_xiao_ble_nrf52840
    shield: KeyballBLE_L
  - board: seeed_xiao_ble_nrf52840
    shield: settings_reset
